### ISSUE TITLE
有人需要你的幫忙

### ISSUE THREAD

**Issue by c2xusnpq6** [L-JINBIN/MT-Translation-Plugin#3] opened 2021-05-18 18:15 UTC
https://forum.xda-developers.com/t/help-me-buy-mt-manager-vip-account.4182395/

**Comment by Aboodhassand** [comment] 2022-09-26 15:42
`https://github.com/L-JINBIN/MT-Translation-Plugin/issues?q=is%3Aopen+is%3Aissue#issue-894651607`

**Comment by Aboodhassand** [comment] 2022-09-26 15:46
> `
Duplicate of #`

**Closed** 2022-10-20 00:00 UTC
